[GR-60088] Add jdk.graal.nativeimage module.
oracle/graal pull request #10380
Opened 2024-12-23 22:09 UTC by graalvmbot

2025-01-10 10:16 UTC, christianhaeubl commented on substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/RuntimeSupport.java
> +    @Override
I think you should move all these new methods to a separate libgraal-specific image singleton that implements `LibGraalRuntimeSupport` (for a normal native image, it does not make sense to use any of these methods).

2025-01-10 11:23 UTC, zapster commented on compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/libgraal/LibGraalFeature.java
> +    public static final String NATIVE_IMAGE_SETTING_KEY_PREFIX = "org.graalvm.nativeimage.setting.";
`jdk.graal.compiler` exports everything (`*`) to `org.graalvm.nativeimage...` which makes of course sense for hosted graal usage. 

If I understand correctly, `LibGraalFeature` is guest graal only. I.e., `org.graalvm.nativeimage...` should not depend on it, or even have access to it, right? Otherwise, we might introduce dependencies from native image to a specific version of `LibGraalFeature` without noticing it.

Currently, we only access `NATIVE_IMAGE_SETTING_KEY_PREFIX` so not a problem. Still, would it make sense to separate it out `LibGraalFeature` to avoid problems?

2025-01-10 12:39 UTC, zapster commented on compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/libgraal/LibGraalFeature.java
> +        }
could we move the singleton initialization into the static initialize or a private static inner class? that way we don't need to do a manual synchronize and the JVM guarantees us that there is only one initialization.

2025-01-14 17:27 UTC, dougxc commented on substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/RuntimeSupport.java
> +    @Override
Ok. Where would you suggest to put `LibGraalRuntimeSupportImpl`? In `substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/libgraal/LibGraalRuntimeSupportImpl.java`?

2025-01-14 17:56 UTC, christianhaeubl commented on substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/RuntimeSupport.java
> +    @Override
Sounds good.

2025-01-14 17:57 UTC, dougxc commented on compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/libgraal/LibGraalFeature.java
> +        }
Can a feature be created and registered by some other means (e.g. search for static field or factory method) instead of by calling the default constructor? Based on my reading of `com.oracle.svm.hosted.FeatureHandler#registerFeature` I think the answer is no?

2025-01-14 17:58 UTC, dougxc commented on substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/RuntimeSupport.java
> +    @Override
Will do.

2025-02-06 09:48 UTC, olpaw requested changes
PR is close to being mergeable. Left some comments.

2025-02-06 09:48 UTC, olpaw commented on compiler/src/jdk.graal.compiler.libgraal/src/jdk/graal/compiler/libgraal/LibGraalFeature.java
> +    public void beforeAnalysis(BeforeAnalysisAccess access) {
Nice! It's now almost pleasant to look at.
No more reflective access to the Graal classes that we want to have in libgraal :partying_face:

2025-02-06 09:48 UTC, olpaw commented on compiler/src/jdk.graal.compiler.libgraal/src/jdk/graal/compiler/libgraal/LibGraalFeature.java
> +    public void duringAnalysis(DuringAnalysisAccess access) {
Yes, `duringAnalysis` is official API but it's something that we want to get rid of in the long run because `duringAnalysis` implementations run single-threaded, thus having the potential to increase static analysis time significantly.

Using `org.graalvm.nativeimage.hosted.Feature.DuringSetupAccess#registerObjectReplacer`s that just return the original unmodified objects but registers them as UnsafeAccessed as a side-effect was not an option?

2025-02-06 09:48 UTC, olpaw commented on compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/serviceprovider/GlobalAtomicLong.java
> +                    long addr = UNSAFE.allocateMemory(Long.BYTES);
Add a comment that this code-path is used when running as graal.jar (not as native-image)

2025-02-06 10:02 UTC, dougxc commented on compiler/mx.compiler/suite.py
> +      "maven": {
Actually, with introduction of `jdk.graal.compiler.core.common.LibGraalSupport`, there is no longer a module dependency from `jdk.graal.compiler` to `jdk.graal.nativeimage`. I'll remove the `maven` attribute until it's clear we need it.

2025-02-06 11:20 UTC, dougxc commented on compiler/src/jdk.graal.compiler.libgraal.loader/src/jdk/graal/compiler/libgraal/loader/HostedLibGraalClassLoader.java
> +                        ModuleReader reader = mr.open();
The `reader` needs to stay open beyond the scope the `HostedLibGraalClassLoader` constructor as it's used by each `ModulePathResource`. I think it's fine to have it cleaned up during JVM shutdown. Or should we add a `close()` method to `LibGraalLoader` and if so, where in NativeImage should it be called?

2025-02-06 11:29 UTC, olpaw commented on compiler/src/jdk.graal.compiler.libgraal.loader/src/jdk/graal/compiler/libgraal/loader/HostedLibGraalClassLoader.java
> +                        ModuleReader reader = mr.open();
> and if so, where in NativeImage should it be called?

You can make ‎use `Feature::cleanup` for that.

2025-02-06 12:26 UTC, dougxc commented on compiler/src/jdk.graal.compiler.libgraal.loader/src/jdk/graal/compiler/libgraal/loader/HostedLibGraalClassLoader.java
> +                        ModuleReader reader = mr.open();
You sure this should be done from `LibGraalFeature.cleanup`? It's not the entity that creates the `HostedLibGraalClassLoader` so how can it be sure that the open `reader` objects won't be used again?

2025-02-06 13:28 UTC, dougxc commented on compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/libgraal/LibGraalFeature.java
> +        }
I ended up removing all need for the `singleton` field.

2025-02-06 13:28 UTC, dougxc commented on compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/libgraal/LibGraalFeature.java
> +    public static final String NATIVE_IMAGE_SETTING_KEY_PREFIX = "org.graalvm.nativeimage.setting.";
Moved to `jdk.graal.compiler.core.common.LibGraalSupport#NATIVE_IMAGE_SETTING_KEY_PREFIX`.

2025-02-06 13:40 UTC, dougxc commented on compiler/src/jdk.graal.compiler.libgraal.loader/src/jdk/graal/compiler/libgraal/loader/HostedLibGraalClassLoader.java
> +    static class Resource {
Done: https://github.com/oracle/graal/pull/10380/commits/c7a51f62f2b20acea23621e780c0f48169e4e147

2025-02-06 13:41 UTC, dougxc commented on compiler/src/jdk.graal.compiler.libgraal.loader/src/jdk/graal/compiler/libgraal/loader/HostedLibGraalClassLoader.java
> +                ModuleFinder libgraalModulePath = ModulePath.of(Stream.of(prop.split(File.pathSeparator)).map(Path::of).toArray(Path[]::new));
Done: https://github.com/oracle/graal/pull/10380/commits/c7a51f62f2b20acea23621e780c0f48169e4e147#diff-5a6170b7e9cf1386c8f286fdd774d960e428b77560fe8ca1cf326060c601617dR201

2025-02-06 13:42 UTC, dougxc commented on compiler/src/jdk.graal.compiler.libgraal/src/jdk/graal/compiler/libgraal/LibGraalFeature.java
> +    public void duringAnalysis(DuringAnalysisAccess access) {
Done: https://github.com/oracle/graal/pull/10380/commits/9e41cfe0d15cb37f043a4240462f34755a6f7f7e

2025-02-06 13:42 UTC, dougxc commented on compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/serviceprovider/GlobalAtomicLong.java
> +                    long addr = UNSAFE.allocateMemory(Long.BYTES);
Done.

2025-02-06 13:43 UTC, dougxc commented on compiler/src/jdk.graal.compiler.libgraal.loader/src/jdk/graal/compiler/libgraal/loader/HostedLibGraalClassLoader.java
>          ClassLoader.registerAsParallelCapable();
Done: https://github.com/oracle/graal/commit/cf9c83dec10b5634dea508877f9ca598933d94b4

2025-02-06 19:10 UTC, dougxc commented on compiler/mx.compiler/suite.py
> +      "maven": {
```
Deploying org.graalvm.nativeimage:library-support...
  File "/b/b/e/mxtool/mx.py", line 31, in <module>
    runpy.run_module("mx")
  File "/cm/shared/apps-ol7/python3/3.8.10/lib/python3.8/runpy.py", line 210, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/cm/shared/apps-ol7/python3/3.8.10/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/b/b/e/mxtool/src/mx/__main__.py", line 49, in <module>
    _main_wrapper()
  File "/b/b/e/mxtool/src/mx/_impl/mx.py", line 18376, in _main_wrapper
    main()
  File "/b/b/e/mxtool/src/mx/_impl/mx.py", line 18360, in main
    retcode = c(command_args)
  File "/b/b/e/mxtool/src/mx/_impl/mx_commands.py", line 145, in __call__
    return self.command_function(*args, **kwargs)
  File "/b/b/e/mxtool/src/mx/_impl/mx.py", line 11650, in maven_deploy
    _maven_deploy_dists(dists, versionGetter, repo, args.settings,
  File "/b/b/e/mxtool/src/mx/_impl/mx.py", line 11390, in _maven_deploy_dists
    pomFile = _tmpPomFile(dist, versionGetter, validateMetadata)
  File "/b/b/e/mxtool/src/mx/_impl/mx.py", line 11043, in _tmpPomFile
    tmp.write(_genPom(dist, versionGetter, validateMetadata))
  File "/b/b/e/mxtool/src/mx/_impl/mx.py", line 10987, in _genPom
    dist.abort(f"Distribution depends on non-maven distribution {dep}")
  File "/b/b/e/mxtool/src/mx/_impl/build/suite/dependency.py", line 209, in abort
    abort(msg, context=self)
  File "/b/b/e/mxtool/src/mx/_impl/support/logging.py", line 277, in abort
    traceback.print_stack()
  File "/b/b/e/graal/substratevm/mx.substratevm/suite.py", line 2133 in definition of NATIVE_IMAGE_BASE:
2025-02-06 18:54:50(+08:33)[ERROR] Process failed with return code 1
Distribution depends on non-maven distribution GRAAL_NATIVEIMAGE
```
Turns out that `jdk.graal.nativeimage` does need to be deployed to maven after all.

2025-02-06 19:36 UTC, dougxc commented on compiler/src/jdk.graal.compiler/src/jdk/graal/compiler/graph/Edges.java
> +    public static long computeIterationMask(Type type, int directCount, long[] offsets) {
This method and the associated constants was moved here from `NodeClass`.

2025-02-07 11:42 UTC, dougxc commented on compiler/src/jdk.graal.compiler.libgraal.loader/src/jdk/graal/compiler/libgraal/loader/HostedLibGraalClassLoader.java
> +                        ModuleReader reader = mr.open();
I resolved this by creating (and closing) a `ModuleReader` for each resource when it's read - the overhead is not noticeable.

2025-02-10 08:26 UTC, olpaw submitted a review, later dismissed

2025-02-10 11:00 UTC, olpaw approved these changes

2025-02-15 11:52 UTC, closed without merging