Add exclude-config option #2535
oracle/graal pull request #3179
Opened 2021-02-02 17:43 UTC by galderz

This PR Replaces #3149.

It uses a more fine grained approach to exclude configuration from jars. A new option `--exclude-config` is added that takes as a value a comma separating a jar name and regular expression of resources to exclude from the given jar. Jar names can include path elements for situations where two jar names have the same name but different leading path.

Examples:
```
--exclude-config foo.jar,META-INF\/native-image\/.*.properties
--exclude-config bar.jar,META-INF\/native-image\/.*.json
--exclude-config foo/example.jar,META-INF\/native-image\/.*.json
--exclude-config bar/example.jar,META-INF\/native-image\/.*.json
```

The approach was agreed with @olpaw on [this slack chat](https://graalvm.slack.com/archives/CN9KSFB40/p1611664256033900).

2021-02-02 18:09 UTC, maxandersen commented
Is there way to use pattern for the jar?

2021-02-02 18:15 UTC, galderz commented
> Is there way to use pattern for the jar?

Not at the moment, but could be added.

2021-02-03 10:14 UTC, olpaw commented
> > Is there way to use pattern for the jar?
> 
> Not at the moment, but could be added.

Be care how you add that so that the separating of the regex for the jarfile and the regex for the resource path is unambiguous. I.e. if the regex of the path would contain a `,` you might mistakenly interpret it as the separator of jarfile-regex and resourcepath-regex. (I know ... `,` is quite unlikely in a regex for a path, but you never know what users are up to). Maybe the easiest solution would be to make the option take two arguments ... like
```
--exclude-config foo/.*\.jar META-INF\/native-image\/.*.json
```

2021-02-08 08:47 UTC, olpaw commented on substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/DefaultOptionHandler.java
> +                final String[] split = excludeConfig.split(",");
If your regex contains a `","` you will only use the first half of it as the second argument to nativeImage.addExcludeConfig. What you need here is
```java
String[] split = excludeConfig.split(",", 2);
```

2021-02-08 08:51 UTC, olpaw commented
> > Is there way to use pattern for the jar?
> 
> Not at the moment, but could be added.

@galderz are you going to change the PR to make the path matching also be based on a regex (as @maxandersen suggested) or do you consider this PR ready as is?

2021-02-08 08:52 UTC, olpaw requested changes
See https://github.com/oracle/graal/pull/3179/files#r571867459

2021-02-17 09:29 UTC, galderz commented
I'm handling this today. I'm going to try to apply @maxandersen's suggestion, along with the split into 2 parameters that @olpaw suggested. That sounds like a good combination.

2021-02-17 10:30 UTC, galderz commented
Updated PR. Added a commit to switch to 2 parameters and hence enable jar files to also be regular expressions. I can squash commits when it's ready to go in.

2021-02-17 10:40 UTC, olpaw approved these changes
LGTM. Please squash the commit so that I can create an internal PR.

2021-02-17 15:13 UTC, galderz commented
Thx @olpaw. Squashed and pushed.

2021-02-17 21:23 UTC, zakkak commented
@galderz it looks like there is a [formatting issue](https://github.com/oracle/graal/runs/1917831543?check_suite_focus=true#step:8:1603)

2021-02-18 09:26 UTC, olpaw commented
> @galderz it looks like there is a [formatting issue](https://github.com/oracle/graal/runs/1917831543?check_suite_focus=true#step:8:1603)

@zakkak is right. This should be fixed before I try to push this to master.
@galderz please adjust the formatting accordingly.

2021-02-19 10:00 UTC, galderz commented
Looking into the formatting issue

2021-02-19 10:41 UTC, galderz commented
How reliable is this formatting automation? When I run `mx eclipseformat -e /opt/eclipse/Eclipse.app/Contents/MacOS/eclipse --primary` locally I see [all these files formatted](https://gist.github.com/galderz/7c00ad5ca67ad6b88afc6d08f335bd15).

2021-02-19 10:43 UTC, galderz commented
Pushed an updated. Formatting should be fixed.

2021-02-19 16:24 UTC, olpaw commented
Your PR passed our gates and is now in the merge queue. ETA Monday

2021-02-20 03:09 UTC, merged