Add registering serialziation API
oracle/graal pull request #3508
Opened 2021-06-23 02:34 UTC by ziyilin

Refactoring serialization code to add APIs for registring serialization target classes at build time. 
Add a new method to register **simple** serialization target class at build time programmatically instead of providing configurations.
The **simple** Class means:
1. Class doesn't have any subclasses. Otherwise, the actual serialization class at run time could be any of its subclasses.
2. Class doesn't have customized `writeObject(ObjectOutputStream)`/`readObject(ObjectInputStream)` method.

2021-06-25 04:54 UTC, mcraj017 commented
@ziyilin please share the issue, this PR will close

2021-06-25 05:13 UTC, ziyilin commented
There is no issue. This PR is an extension to the existing serialization feature. It enables other features can register new serialization target classes programamtically.

2021-06-28 04:09 UTC, mcraj017 commented
@ziyilin thanks for the clarification, we will review it and let you know our thoughts

2021-06-28 08:05 UTC, olpaw commented on substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/serialize/SerializationSupport.java
> +    @Platforms(Platform.HOSTED_ONLY.class) private final Map<Class<?>, Boolean> deniedClasses;
Adding any field to `SerializationSupport` that is not needed at image runtime is a design flaw. Please move these fields to `SerializationBuilder` where they actually belong.

2021-06-28 08:09 UTC, olpaw commented on substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/serialize/hosted/SerializationBuilder.java
> +package com.oracle.svm.reflect.serialize.hosted;
I'm OK with moving `SerializationBuilder` into it's own source file but please isolate such changes into an individual commit that contains only the moving and nothing else. Having all these changes mashed into one commit makes it hard to see what else got changed in `SerializationBuilder`.

2021-06-28 08:12 UTC, olpaw commented on substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/serialize/hosted/SerializationFeature.java
> +        ImageSingletons.add(SerializationRegistry.class, support);
`SerializationBuilder` is responsible for building up the data in `SerializationSupport` thus the `SerializationBuilder` singleton should be registers by the `SerializationBuilder` (like it was before)

2021-06-28 08:13 UTC, olpaw commented on substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/serialize/hosted/SerializationFeature.java
> +                support.putDeniedClass(serializationTargetClass, true);
See https://github.com/oracle/graal/pull/3508/files?diff=unified&w=1#r659566975

2021-06-28 08:13 UTC, olpaw requested changes
See comments

2021-06-29 15:00 UTC, kkriske commented
This adds the same functionality as https://github.com/oracle/graal/pull/3050 right? I'm fine with either as long as the issue itself finally gets some attention again... Just sad to see that it was even needed to make a second implementation.
While I'm in no position to give a review, I do think some proper public API should be added, similar to the RuntimeReflection API.

2021-06-29 15:44 UTC, olpaw commented
> This adds the same functionality as #3050 right? I'm fine with either as long as the issue itself finally gets some attention again... Just sad to see that it was even needed to make a second implementation.
> While I'm in no position to give a review, I do think some proper public API should be added, similar to the RuntimeReflection API.

Hi @kkriske, yes this is similar to what you started a while ago. If you decide to go back to your PR and bring it up to date I will re-review it. I suggest whatever PR is more readable, well-structured, concise and complete will get merged.

@ziyilin in case @kkriske decides to take his PR up again I would like to also get feedback from your side on his PR (i.e. if it fulfills the requirements that made you submit this PR). The same is also true the other way around (@kkriske s feedback on this PR is very welcome).

2021-06-29 16:08 UTC, ziyilin commented
Good to know @kkriske is working on the similar feature. I have glanced over @kkriske's PR. I think the major difference is my PR  provides an API (https://github.com/oracle/graal/pull/3508/commits/973b4e58ea1591431734e4f6fa72b565cf9ecc27#diff-28427c7ead1756a10e29962510df1ff3e8b029a35238a47d7e6553b1ad9dbf49R110) to register a Class and all the relative classes into serializations. 
Our PRs conflict a lot. As @kkriske's has been proposed a while ago, I think his PR should get processed first. Then I can add my new feature based on his changes on the master.

2021-06-29 16:12 UTC, olpaw commented
> I even asked to give me a heads-up when there would be time to pick it up on your side

Yea, I saw that ... now :wink: ... please tag me in messages if you want to make sure I will really see them.
You can also ping me on public slack https://www.graalvm.org/slack-invitation/

> to avoid my endless frustrating cycle of fixing merge conflicts just to wait for the next conflicts.

Back then serialization was still new and a lot of rewriting needed to happen before it was sufficiently stable. Nowadays the chance you will run into merge conflicts with master in this part of our codebase is much lower.

2021-08-10 07:07 UTC, kkriske commented
@ziyilin #3050 has been merged, so you should be able to pick this back up.

2021-08-10 07:41 UTC, olpaw commented
@ziyilin please reopen (and rebase) if you need additional features on top of the serialization API provided by @kkriske

2021-08-10 07:41 UTC, closed without merging

2021-09-08 09:10 UTC, ziyilin commented
I have opened a new PR https://github.com/oracle/graal/pull/3508