updated hyperlink for VS Code extension
oracle/graal pull request #3739
Opened 2021-08-30 17:42 UTC by The-Alchemist

2021-09-06 09:08 UTC, oubidar-Abderrahim requested changes

2021-09-07 00:11 UTC, The-Alchemist commented on README.md
> +* [VS Code](https://github.com/graalvm/vscode-extensions/README.md) provides extensions to Visual Studio Code that support development of polyglot applications using GraalVM.
Sorry about that.  Pushed a fix.

2021-09-07 16:43 UTC, fniephaus commented
Thanks for the PR, @The-Alchemist! We'll update the README with a fix soon (tracked internally via GR-33619).

2022-01-02 17:12 UTC, fniephaus commented
Fixed via https://github.com/oracle/graal/commit/416facfceb8de73d9cd8f1ea01f754aeaf5913de. Thanks again for the PR!

2022-01-02 17:12 UTC, closed without merging