[GR-41977] Adapt to JVMCI API changes.
oracle/graal pull request #5455
Opened 2022-11-17 00:21 UTC by graalvmbot

2022-11-18 19:22 UTC, zakkak requested changes
Hello @dougxc @christianwimmer, are there any plans to backport the corresponding JVMCI changes to OpenJDK 17? If not, could we please use a more flexible approach to avoid breaking compatibility with JDK 17?

2022-11-18 19:22 UTC, zakkak commented on compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/meta/HotSpotSnippetReflectionProvider.java
> +        return runtime().getMirror(method);
This results in:

```
/home/runner/work/mandrel/mandrel/mandrel/compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/meta/HotSpotSnippetReflectionProvider.java:134: error: incompatible types: ResolvedJavaMethod cannot be converted to ResolvedJavaType
        return runtime().getMirror(method);
```

When building with JDK 17 (both OpenJDK and LabsJDK).

See https://github.com/graalvm/mandrel/actions/runs/3499526212/jobs/5861191268#step:8:445 and https://github.com/graalvm/mandrel/actions/runs/3499602031/jobs/5861349246#step:7:330, respectively.

2022-11-18 19:22 UTC, zakkak commented on compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/meta/HotSpotSnippetReflectionProvider.java
> +        return runtime().getMirror(field);
This results in:

```
/home/runner/work/mandrel/mandrel/mandrel/compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/meta/HotSpotSnippetReflectionProvider.java:142: error: incompatible types: ResolvedJavaField cannot be converted to ResolvedJavaType
        return runtime().getMirror(field);
```

When building with JDK 17 (both OpenJDK and LabsJDK).

See https://github.com/graalvm/mandrel/actions/runs/3499526212/jobs/5861191268#step:8:445 and https://github.com/graalvm/mandrel/actions/runs/3499602031/jobs/5861349246#step:7:330, respectively.

2022-11-23 15:21 UTC, jerboaa commented
Thanks for the heads-up. Looking into it.

2022-11-23 15:43 UTC, christianwimmer commented
The current plan is that nothing from the current master branch will be released anymore based on JDK 17. We are switching to "release new GraalVM versions only with the latest Java version", i.e., GraalVM 23.0 will be based (and only based) on Java 20.

But in case that plan changes, or you want to release something based on JDK 17, there are only a few small OpenJDK issues that you need to backport into OpenJDK 17:
* https://bugs.openjdk.org/browse/JDK-8296958
* https://bugs.openjdk.org/browse/JDK-8296961
* https://bugs.openjdk.org/browse/JDK-8296960
* https://bugs.openjdk.org/browse/JDK-8296956
* https://bugs.openjdk.org/browse/JDK-8296967

2022-11-25 16:07 UTC, jerboaa commented
> * https://bugs.openjdk.org/browse/JDK-8296958
> * https://bugs.openjdk.org/browse/JDK-8296961
> * https://bugs.openjdk.org/browse/JDK-8296960
> * https://bugs.openjdk.org/browse/JDK-8296956
> * https://bugs.openjdk.org/browse/JDK-8296967

FWIW, all of these have been either backported to the `jdk17u-dev` tree already or are in progress of getting integrated. Some waiting for approvals.

2022-12-15 09:46 UTC, zakkak commented
@jerboaa it looks like all the listed patches have been backported and will be part of 17.0.6. Is that correct? Can this PR be integrated?

FWIW Mandrel seems to build fine with this patch and OpenJDK 17.0.6-beta+6-202212140702 (see https://github.com/graalvm/mandrel/actions/runs/3702797693/jobs/6273484993)

2022-12-15 09:48 UTC, jerboaa commented
> @jerboaa it looks like all the listed patches have been backported and will be part of 17.0.6. Is that correct?

Correct.

2024-01-22 11:51 UTC, fniephaus commented
Does this still need to be backported to JDK 17?

2024-01-22 11:51 UTC, closed without merging

2024-01-22 13:19 UTC, jerboaa commented
> Does this still need to be backported to JDK 17?

AFAIK, all changes are in OpenJDK `17.0.6` and better. So no.

2024-01-22 14:24 UTC, fniephaus commented
> AFAIK, all changes are in OpenJDK 17.0.6 and better. So no.

Ok good, I thought this PR is about adapting JVMCI API changes in GraalVM and that needs to be backported to work with OpenJDK 17.0.6 or later.