Cast unsigned values explicitly to avoid signed extension
oracle/graal pull request #5966
Opened 2023-02-13 16:46 UTC by koutheir

Cast unsigned values, stored in smaller types, to `long` using zero-extension instead of Java's default sign extension.

2023-02-13 21:11 UTC, christianwimmer requested changes

2023-02-13 22:58 UTC, koutheir commented on substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/heap/InstanceReferenceMapEncoder.java
> +        writeBuffer.putU4(Integer.toUnsignedLong(refsCount));
If `refsCount` is an unsigned number, and it must be converted to a `long` for the function call, then the conversion needs to be a zero extension, not a signed extension.

2023-05-03 14:44 UTC, gilles-duboscq commented on substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/heap/InstanceReferenceMapEncoder.java
> +        writeBuffer.putU4(Integer.toUnsignedLong(refsCount));
Maybe the assertion that `refsCount >= 0` above is enough?

2023-05-04 14:33 UTC, koutheir commented on substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/heap/InstanceReferenceMapEncoder.java
> +        writeBuffer.putU4(Integer.toUnsignedLong(refsCount));
I wouldn't call the assertion enough, but it surely will detect cases where `refsCount` is negative or huge, as long as assertions are explicitly enabled when running the code, and that is **not** the default. What I'm fixing here is the extension from `int` to `long` necessary at the call site to `putU4()`: that has to be a zero-extension, not a sign-extension.

2024-05-31 06:44 UTC, closed without merging