Add documenation for native memory tracking (NMT)
oracle/graal pull request #9788
Opened 2024-09-30 15:11 UTC by roberttoyonaga

### Summary
Adding some documentation for NMT.  This should be added to GraalVM for JDK 23. Thanks!

2024-09-30 15:12 UTC, roberttoyonaga commented
Hi @olyagpl ! Can you please have a look at this when you have time? Thanks!

2024-10-01 16:04 UTC, olyagpl commented on docs/reference-manual/native-image/NMT.md
> +In most cases, both the CPU and memory overhead of NMT will be quite minimal. There is an overhead of 16B per malloc allocation (to accommodate malloc headers) that is reclaimed once the memory is fr
In practice, this does not amount to very much since Substrate VM does not make many allocations.

2024-10-01 16:14 UTC, olyagpl commented on docs/reference-manual/native-image/NMT.md
> +$jfr print --events jdk.NativeMemoryUsagePeak recording.jfr
```suggestion
jfr print --events jdk.NativeMemoryUsagePeak recording.jfr 
```

2024-10-01 16:16 UTC, olyagpl commented on docs/reference-manual/native-image/NMT.md
> +To use these JFR events for NMT, JFR must be included as a feature at build time and started at runtime.
To use these JFR events for NMT, JFR must be included as a feature at build time and started at runtime. (Learn more in [JDK Flight Recorder (JFR) with Native Image](JFR.md)).

2024-10-01 16:18 UTC, olyagpl commented on docs/reference-manual/native-image/NMT.md
> +
Add one more bullet point:
```markdown
 - [Debugging and Diagnostics](DebuggingAndDiagnostics.md)
```

2024-10-01 16:19 UTC, olyagpl commented on docs/reference-manual/native-image/NMT.md
> +
@roberttoyonaga, could you please also add a link to "Native Memory Tracking (NMT) with Native Image" in the DebuggingAndDiagnostics.md file?

2024-10-01 16:22 UTC, olyagpl commented
@roberttoyonaga, I left some suggestions. Thank you for your contribution! In the description, you mention it should be added/backported to the GraalVM for JDK 23 docs, is that correct?

2024-10-01 16:38 UTC, roberttoyonaga commented on docs/reference-manual/native-image/NMT.md
> +To build a native executable with NMT, use the `--enable-monitoring=nmt` option. If NMT is included at build time, it will always be enabled at runtime. This is different than OpenJDK which allows fo
It's sort of the same. However, I wanted to make a distinction since the user would be interacting with the `java` not hotspot directly.

2024-10-01 16:40 UTC, roberttoyonaga commented on docs/reference-manual/native-image/NMT.md
> +In OpenJDK, NMT has two modes: summary and detailed. Currently in Native Image, only NMT summary mode is supported. Detailed mode, which enables callsite tracking, is not available. Capturing baselin
Yes I'll change this to Hotspot

2024-10-01 16:54 UTC, roberttoyonaga commented on docs/reference-manual/native-image/NMT.md
> +A limitation Native Image NMT shares with OpenJDK is that it can only track allocations at the VM-level and those made with `Unsafe#allocateMemory(long)`. For example, if library code or application
Sounds good! Applied it.

2024-10-01 16:57 UTC, roberttoyonaga commented on docs/reference-manual/native-image/NMT.md
> +In most cases, both the CPU and memory overhead of NMT will be quite minimal. There is an overhead of 16B per malloc allocation (to accommodate malloc headers) that is reclaimed once the memory is fr
Thanks! Applied your suggestion!

2024-10-01 17:06 UTC, roberttoyonaga commented on docs/reference-manual/native-image/NMT.md
> +Only malloc tracking is available in GraalVM for JDK 23. Virtual memory tracking is available in early access releases.
I added a link to the Community edition dev builds here too

2024-10-01 17:07 UTC, roberttoyonaga commented
Thank you for the review @olyagpl ! I've applied your suggestions and updated the doc

2024-10-01 17:09 UTC, roberttoyonaga commented
> @roberttoyonaga, I left some suggestions. Thank you for your contribution! In the description, you mention it should be added/backported to the GraalVM for JDK 23 docs, is that correct?

Yes, that's right. NMT is also supported in GraalVM for JDK 23 so these docs should be backported to that version too. No content needs to be changed for the backport though.

2024-10-01 17:27 UTC, olyagpl requested changes
Some minor leftovers I missed. Other than that, I'm going to "post-process" this pull request from my end (open an internal PR, add a new page to the website navigation) and get back to you.

2024-10-01 17:27 UTC, olyagpl commented on docs/reference-manual/native-image/NMT.md
> +In practice, this does not amount to very much since SubstrateVM does not make many allocations.
```suggestion
In practice, this does not amount to very much since Substrate VM does not make many allocations.
```

2024-10-01 17:27 UTC, olyagpl commented on docs/reference-manual/native-image/NMT.md
> +You may need to enable experimental events in software like JDK Mission control in order to view them.
```suggestion
You may need to enable experimental events in software like JDK Mission Control to view them.
```

2024-10-01 17:27 UTC, olyagpl commented on docs/reference-manual/native-image/NMT.md
> +To use these JFR events for NMT, JFR must be included as a feature at build time and started at runtime.(Learn more in [JDK Flight Recorder (JFR) with Native Image](JFR.md)).
```suggestion
To use these JFR events for NMT, JFR must be enabled at build time and started at runtime. (Learn more in [JDK Flight Recorder (JFR) with Native Image](JFR.md)).
```

2024-10-01 19:48 UTC, olyagpl approved these changes

2024-10-10 17:43 UTC, closed without merging

2024-10-10 18:33 UTC, roberttoyonaga commented
That's great! Thank you @olyagpl !